# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\zhang\OneDrive\Code\SR\ui\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

from PyQt5.QtGui import QFont

url = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # 文件夹


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        # print(url)
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(980, 569)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(url, "./resource/icons/neu.png")), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        mainWindow.setStyleSheet("background-color: rgb(63, 152, 220);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.titleLabel.setFont(QFont('Arial', -1, 200))
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet('''
        color: black; /* 设置文字颜色为灰黑色 /
        font-weight: bold; / 加粗文字 /
        font-family: "Arial Black", sans-serif; / 设置字体为艺术字体 /
        text-shadow: 3px 3px 4px #888888; / 设置文字阴影 */
        font-size: 35px;
        ''')

        # self.titleLabel.setStyleSheet('''
        #     color: ; /* 设置文字颜色为亮蓝色 */
        #     font-weight: bold; /* 加粗文字 */
        #     font-family: "楷体";
        #     text-shadow: 2px 2px 4px #000000; /* 设置文字阴影 */
        #     font-size: 35px
        # ''')
        self.titleLabel.setGeometry(QtCore.QRect(0, 0, 980, 260))  # 设置titleLabel与centralwidget大小一致
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setText("基于意图的 SRv6 配置综合系统")

        self.ana_button = QtWidgets.QPushButton(self.centralwidget)
        self.ana_button.setGeometry(QtCore.QRect(30, 250, 190, 120))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(13)
        self.ana_button.setFont(font)
        self.ana_button.setStyleSheet("background-color: rgb(240, 240, 240);"
                                        "border-radius: 10px;"
                                        "QPushButton#ana_button:hover {"
                                        "background-color: rgb(200, 200, 200);"
                                        "color: red;"
                                        "}")

        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(url, "./resource/icons/file.png")), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.ana_button.setIcon(icon1)
        self.ana_button.setIconSize(QtCore.QSize(70, 70))
        self.ana_button.setObjectName("ver_button")

        self.isis_syn_button = QtWidgets.QPushButton(self.centralwidget)
        self.isis_syn_button.setGeometry(QtCore.QRect(250, 250, 220, 120))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(13)
        font.setStrikeOut(False)
        self.isis_syn_button.setFont(font)
        self.isis_syn_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.isis_syn_button.setStyleSheet("background-color: rgb(240, 240, 240);border-radius: 10px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(url, "./resource/icons/policy.png")), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.isis_syn_button.setIcon(icon2)
        self.isis_syn_button.setIconSize(QtCore.QSize(70, 70))
        self.isis_syn_button.setObjectName("isis_syn_button")

        self.syn_button = QtWidgets.QPushButton(self.centralwidget)
        self.syn_button.setGeometry(QtCore.QRect(500, 250, 220, 120))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(13)
        font.setStrikeOut(False)
        self.syn_button.setFont(font)
        self.syn_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.syn_button.setStyleSheet("background-color: rgb(240, 240, 240);border-radius: 10px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(url, "./resource/icons/SRv6.png")), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.syn_button.setIcon(icon2)
        self.syn_button.setIconSize(QtCore.QSize(70, 70))
        self.syn_button.setObjectName("syn_button")

        self.rec_button = QtWidgets.QPushButton(self.centralwidget)
        self.rec_button.setGeometry(QtCore.QRect(760, 250, 190, 120))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(13)
        self.rec_button.setFont(font)
        self.rec_button.setStyleSheet("background-color: rgb(240, 240, 240);border-radius: 10px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(os.path.join(url, "./resource/icons/record.png")), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.rec_button.setIcon(icon3)
        self.rec_button.setIconSize(QtCore.QSize(70, 100))
        self.rec_button.setObjectName("rec_button")


        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "基于意图的SRv6配置综合系统"))

        self.ana_button.setText(_translate("mainWindow", "意图解析"))
        self.isis_syn_button.setText(_translate("mainWindow", "IS-IS配置综合"))
        self.syn_button.setText(_translate("mainWindow", "SRv6配置综合"))
        self.rec_button.setText(_translate("mainWindow", "日志记录"))


