# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\zhang\OneDrive\Code\SR\ui\recordWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets

url = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # 文件夹


class Ui_Rec_Dialog(object):
    def setupUi(self, Rec_Dialog):
        Rec_Dialog.setObjectName("Rec_Dialog")
        Rec_Dialog.resize(831, 477)
        Rec_Dialog.setMinimumSize(QtCore.QSize(721, 441))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(url, "./resource/icons/neu.png")), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        Rec_Dialog.setWindowIcon(icon)
        Rec_Dialog.setStyleSheet("background-color: rgb(89, 166, 228);\n"
                                 "background-color: rgb(235, 235, 235);")
        Rec_Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Rec_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.record_tableWidget = QtWidgets.QTableWidget(Rec_Dialog)
        self.record_tableWidget.setMinimumSize(QtCore.QSize(721, 441))
        self.record_tableWidget.setMaximumSize(QtCore.QSize(8010, 441))
        self.record_tableWidget.setAccessibleDescription("")
        self.record_tableWidget.setAutoFillBackground(False)
        self.record_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.record_tableWidget.setTabKeyNavigation(True)
        self.record_tableWidget.setProperty("showDropIndicator", False)
        self.record_tableWidget.setDragEnabled(True)
        self.record_tableWidget.setAlternatingRowColors(True)
        self.record_tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.record_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.record_tableWidget.setShowGrid(True)
        self.record_tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.record_tableWidget.setWordWrap(True)
        self.record_tableWidget.setRowCount(15)
        self.record_tableWidget.setColumnCount(7)
        self.record_tableWidget.setObjectName("record_tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.record_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.record_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.record_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.record_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.record_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.record_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.record_tableWidget.setHorizontalHeaderItem(6, item)
        self.record_tableWidget.horizontalHeader().setVisible(True)
        self.record_tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.record_tableWidget.horizontalHeader().setHighlightSections(True)
        self.record_tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.record_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.record_tableWidget.verticalHeader().setVisible(False)
        self.record_tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.record_tableWidget, 0, 0, 1, 1)

        self.retranslateUi(Rec_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Rec_Dialog)

    def retranslateUi(self, Rec_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Rec_Dialog.setWindowTitle(_translate("Rec_Dialog", "AutoSRv6日志记录"))
        self.record_tableWidget.setSortingEnabled(False)
        item = self.record_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Rec_Dialog", "序号"))
        item = self.record_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Rec_Dialog", "输入文件位置"))
        item = self.record_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Rec_Dialog", "开始时间"))
        item = self.record_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Rec_Dialog", "操作类型"))
        item = self.record_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Rec_Dialog", "所用时长"))
        item = self.record_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Rec_Dialog", "结果"))
        item = self.record_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Rec_Dialog", "输出文件位置"))
