# -*- coding: utf-8 -*-
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets
url = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # 文件夹


class Ui_Syn_Dialog(object):
    def setupUi(self, Syn_Dialog):
        Syn_Dialog.setObjectName("Syn_Dialog")
        Syn_Dialog.resize(916, 573)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(url, "./resource/icons/neu.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Syn_Dialog.setWindowIcon(icon)
        Syn_Dialog.setStyleSheet("background-color: rgb(240, 240, 240);")

        self.start_button = QtWidgets.QPushButton(Syn_Dialog)
        self.start_button.setGeometry(QtCore.QRect(600, 40, 100, 60))
        self.start_button.setAutoFillBackground(False)
        self.start_button.setStyleSheet("QPushButton#start_button {"
        "background-color: rgb(63, 152, 220);"
        "color: white;"
        "font-size: 18px;"  
        "font-weight: bold;"
        "border: 2px solid white;"
        "border-radius: 10px;"
        "}"
        "QPushButton#start_button:hover {"
        "background-color: white;"
        "color: #4CAF50;"
        "}")
        self.start_button.setCheckable(False)
        self.start_button.setObjectName("start_button")

        self.ana_button = QtWidgets.QPushButton(Syn_Dialog)
        self.ana_button.setGeometry(QtCore.QRect(750, 40, 100, 60))
        self.ana_button.setAutoFillBackground(False)
        self.ana_button.setStyleSheet("QPushButton#ana_button {"
                                      "background-color:rgb(63, 152, 220);"
                                      
                                      "color: white;"
                                      "font-size: 18px;"
                                      "font-weight: bold;"
                                      "border: 2px solid white;"
                                      "border-radius: 10px;"
                                      "}"
                                      "QPushButton#ana_button:hover {"
                                      "background-color: white;"
                                      "color: #4CAF50;"
                                      "}")

        self.ana_button.setCheckable(False)
        self.ana_button.setObjectName("ana_button")





        self.layoutWidget = QtWidgets.QWidget(Syn_Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(450, 150, 451, 411))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")   #用于设置对象的名称以便在后续的代码中引用。
       # self.layoutWidget.setStyleSheet("background-color: red;")

        self.label_2 = QtWidgets.QLabel(self.layoutWidget) # 对应输出结果的那个标签标题
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)

        self.output_browser = QtWidgets.QTextBrowser(self.layoutWidget)  #输出结果的那个框
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.output_browser.setFont(font)
        self.output_browser.setAutoFillBackground(True)
        self.output_browser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.output_browser.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.output_browser.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.output_browser.setLineWrapColumnOrWidth(0)
        self.output_browser.setObjectName("output_browser")
        self.gridLayout_4.addWidget(self.output_browser, 1, 0, 1, 1)



        self.layoutWidget1 = QtWidgets.QWidget(Syn_Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 565, 85))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
       # self.topo_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        #self.layoutWidget1.setStyleSheet("background-color: rgb(255, 255, 255);")
        font = QtGui.QFont()
        font.setFamily("Consolas")
#         self.topo_lineEdit.setFont(font)
#         self.topo_lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
#         self.topo_lineEdit.setAutoFillBackground(False)
#         self.topo_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
#         self.topo_lineEdit.setReadOnly(True)
#         self.topo_lineEdit.setObjectName("topo_lineEdit")
#         self.gridLayout.addWidget(self.topo_lineEdit, 0, 0, 1, 1)
#
#         self.topo_button = QtWidgets.QPushButton(self.layoutWidget1)
#         self.topo_button.setAutoFillBackground(False)
#         self.topo_button.setStyleSheet("background-color: rgb(225, 225, 225);\n"
# "selection-background-color: rgb(229, 241, 251);")
#         self.topo_button.setCheckable(False)
#         self.topo_button.setObjectName("topo_button")
#         self.gridLayout.addWidget(self.topo_button, 0, 1, 1, 1)

        self.policy_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.policy_lineEdit.setFont(font)
        self.policy_lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.policy_lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.policy_lineEdit.setAutoFillBackground(False)
        self.policy_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.policy_lineEdit.setReadOnly(True)
        self.policy_lineEdit.setObjectName("policy_lineEdit")
        self.gridLayout.addWidget(self.policy_lineEdit, 0, 0, 1, 1)

        self.policy_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.policy_button.setAutoFillBackground(False)
        self.policy_button.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"selection-background-color: rgb(229, 241, 251);")
        self.policy_button.setCheckable(False)
        self.policy_button.setChecked(False)
        self.policy_button.setObjectName("policy_button")
        self.gridLayout.addWidget(self.policy_button, 0, 1, 1, 1)

        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)

        self.layoutWidget2 = QtWidgets.QWidget(Syn_Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(7, 150, 431, 411))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)

        self.input_browser = QtWidgets.QTextBrowser(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.input_browser.setFont(font)
        self.input_browser.setAutoFillBackground(True)
        self.input_browser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_browser.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.input_browser.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.input_browser.setObjectName("input_browser")
        self.gridLayout_3.addWidget(self.input_browser, 1, 0, 1, 1)



        self.retranslateUi(Syn_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Syn_Dialog)

    def retranslateUi(self, Syn_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Syn_Dialog.setWindowTitle(_translate("Syn_Dialog", "AutoSRv6意图解析"))
        self.start_button.setText(_translate("Syn_Dialog", "读取"))
        self.ana_button.setText(_translate("Syn_Dialog", "解析"))
        self.label_2.setText(_translate("Syn_Dialog", "意图解析结果："))
        self.output_browser.setDocumentTitle(_translate("Syn_Dialog", "输入信息"))
        # self.topo_lineEdit.setText(_translate("Syn_Dialog", "请输入拓扑文件路径"))
        # self.topo_button.setText(_translate("Syn_Dialog", "打开"))
        self.policy_lineEdit.setText(_translate("Syn_Dialog", "请输入意图文件路径"))
        self.policy_button.setText(_translate("Syn_Dialog", "打开"))
        self.label.setText(_translate("Syn_Dialog", "输入意图信息："))
        self.input_browser.setDocumentTitle(_translate("Syn_Dialog", "输入配置意图信息"))
